
system:
  env: public
  addr: 8888
  dbType: mysql
jwt:
  signing-key: abc
  expires-time: 60s
  buffer-time: 20
  issuer: louis
#  日志输出配置
zap:
  level: debug
  director: .log
  log-in-console: true
  show-line: true
#  mysql 配置
mysql:
  db-name: louis_coub
  path: localhost
  port: 3306
  config:
  username: root
  password: "!QAZ2wsx"
  prefix:
  engine: InnoDB
